namespace: "namespace_name"
name: "collection_name"
version: "1.0.12"
readme: "README.md"
authors:
    - ANAND KUMAR
dependencies: []
license:
    - "MIT"
tags:
    - demo
    - collection
repository: " https://github.com/akyhcs/ansible_assignment"
